apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80          # Ingress가 연결할 포트 (ClusterIP의 외부 포트)
      targetPort: 80    # Deployment의 containerPort
  type: ClusterIP
